name: artGen
channels:
  - javascript
dependencies:
  - pylint
  - jupyter
  - tensorflow
  - matplotlib
  - numpy
  - pandas
  - pip
  - pip:
    - tensorflow-probability==0.10.1
    - tensorflow-datasets